accounts/urls.py
from django.urls import path,include
from . import views

app_name='accounts'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index,name='index'),
    path('add_advertise', views.add_advertise,name='add_advertise'),
    path('all_products', views.product_list,name='product_list'),
    path('all_products/search', views.search,name='search'),
    path('all_products/<slug:category_slug>', views.product_list,name='product_list_category'),
    path('<slug:product_slug>', views.product_detail,name='product_detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls',namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{message.tags}} alert-dismissable text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert">
                    <span style="font-size:40px;margin-top:0;" aria-hidden="true">&times;</span>
                </button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{message}}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<!--footer section start-->
<footer>
  <div class="footer-top">
    <div class="container">
      <div class="foo-grids">
        <div class="col-md-3 footer-grid">
          <h4 class="footer-head">Who We Are</h4>
          <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          <p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
        </div>
        <div class="col-md-3 footer-grid">
          <h4 class="footer-head">Help</h4>
          <ul>
            <li><a href="howitworks.html">How it Works</a></li>
            <li><a href="sitemap.html">Sitemap</a></li>
            <li><a href="faq.html">Faq</a></li>
            <li><a href="feedback.html">Feedback</a></li>
            <li><a href="contact.html">Contact</a></li>
            <li><a href="typography.html">Shortcodes</a></li>
          </ul>
        </div>
        <div class="col-md-3 footer-grid">
          <h4 class="footer-head">Information</h4>
          <ul>
            <li><a href="regions.html">Locations Map</a></li>
            <li><a href="terms.html">Terms of Use</a></li>
            <li><a href="popular-search.html">Popular searches</a></li>
            <li><a href="privacy.html">Privacy Policy</a></li>
          </ul>
        </div>
        <div class="col-md-3 footer-grid">
          <h4 class="footer-head">Contact Us</h4>
          <span class="hq">Our headquarters</span>
          <address>
            <ul class="location">
              <li><span class="glyphicon glyphicon-map-marker"></span></li>
              <li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
              <div class="clearfix"></div>
            </ul>
            <ul class="location">
              <li><span class="glyphicon glyphicon-earphone"></span></li>
              <li>+0 561 111 235</li>
              <div class="clearfix"></div>
            </ul>
            <ul class="location">
              <li><span class="glyphicon glyphicon-envelope"></span></li>
              <li><a href="mailto:info@example.com">mail@example.com</a></li>
              <div class="clearfix"></div>
            </ul>
          </address>
        </div>
        <div class="clearfix"></div>
      </div>
    </div>
  </div>
  <div class="footer-bottom text-center">
  <div class="container">
    <div class="footer-logo">
      <a href="{% url 'products:index' %}"><span>Re</span>sale</a>
    </div>
    <div class="footer-social-icons">
      <ul>
        <li><a class="facebook" href="#"><span>Facebook</span></a></li>
        <li><a class="twitter" href="#"><span>Twitter</span></a></li>
        <li><a class="flickr" href="#"><span>Flickr</span></a></li>
        <li><a class="googleplus" href="#"><span>Google+</span></a></li>
        <li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
      </ul>
    </div>
    <div class="copyrights">
      <p> © 2020 Resale. All Rights Reserved | <a href="https://github.com/MoatazMohamedAllam"> Moataz-14</a></p>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
</footer>
    <!--footer section end-->

templates/partials/_navbar.html
<div class="header">
  <div class="container">
    <div class="logo">
      <a href="{% url 'products:index' %}"><span>Re</span>sale</a>
    </div>
    <div class="header-right">
      {% if user.is_authenticated %}
        <a class="account" style="margin-right:20px;" href="{% url 'accounts:profile' %}">My Profile</a>
        <a class="account" style="margin-right:20px;" href="{% url 'products:add_advertise' %}">Post Free Ad</a>
        <a class="account" href="javascript:{document.getElementById('logout').submit()}">
          <i class="fas fa-sign-out-alt"></i>Logout
        </a>
        <form id="logout" action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <input type="hidden">
        </form>
      {% else %}
        <a class="account" href="{% url 'accounts:login' %}">My Account</a>
      {% endif %}
  </div>
  </div>
</div>