accounts/urls.py
from django.urls import path,include
from . import views

app_name='accounts'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('profile/',views.profile,name='profile'),
    path('logout/',views.logout,name='logout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.index,name='index'),
    path('add_advertise', views.add_advertise,name='add_advertise'),
    path('all_products', views.product_list,name='product_list'),
    path('all_products/search', views.search,name='search'),
    path('all_products/<slug:category_slug>', views.product_list,name='product_list_category'),
    path('<slug:product_slug>', views.product_detail,name='product_detail'),
]

src/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls',namespace='products')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from .choices import cities



class Product(models.Model):
    CONDITION_TYPE =(
        ('New','New'),
        ('Used','Used'),
    )


    def get_image_path(instance,filename):
        name, ext = filename.split('.')
        image_path = 'product_photos/{prod_name}/{photo_name}.{ext}'.format(prod_name=instance.name,photo_name=name,ext=ext)
        return image_path

    name = models.CharField(max_length=100)
    description = models.TextField(max_length=500)
    condition = models.CharField(max_length=100,choices=CONDITION_TYPE)
    price = models.IntegerField()
    city_name = models.CharField(max_length=150,choices=cities,blank=True,null=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    created = models.DateTimeField(default = timezone.now)
    category = models.ForeignKey('Category',on_delete=models.SET_NULL,null=True)
    brand = models.ForeignKey('Brand',on_delete=models.SET_NULL,null=True)
    photo_main = models.ImageField(upload_to=get_image_path)
    photo_1 = models.ImageField(upload_to=get_image_path,blank=True)
    photo_2 = models.ImageField(upload_to=get_image_path,blank=True)
    photo_3 = models.ImageField(upload_to=get_image_path,blank=True)
    photo_4 = models.ImageField(upload_to=get_image_path,blank=True)
    photo_5 = models.ImageField(upload_to=get_image_path,blank=True)
    photo_6 = models.ImageField(upload_to=get_image_path,blank=True)
    slug = models.SlugField(blank=True,null=True)
    isTrending = models.BooleanField(default=False)

    def save(self,*args,**kwargs):
        self.slug =slugify(self.name)
        super(Product,self).save(*args,**kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'



#########################################################

class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='category_images/',blank=True,null=True)
    slug = models.SlugField(blank=True,null=True)

    def save(self,*args,**kwargs):
        self.slug =slugify(self.name)
        super(Category,self).save(*args,**kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

#########################################################

class Brand(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'

product/forms.py
from django import forms
from .models import Product



class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields= '__all__'

product/views.py
from django.shortcuts import render,redirect
from .models import Product,Category,Brand
from django.core.paginator import EmptyPage,PageNotAnInteger,Paginator
from django.db.models import Count
from .choices import cities_choices
from django.contrib import messages,auth
from django.contrib.auth.decorators import login_required



def index(request):
    category_list = Category.objects.all()
    trending_products = Product.objects.filter(isTrending=True)

    context = {
        'category_list':category_list,
        'trending_products': trending_products
    }
    return render(request,'product/index.html',context)


def product_list(request,category_slug=None):
    productList = Product.objects.order_by('-created')
    categoryList = Category.objects.annotate(total_products=Count('product'))
    trending_products = Product.objects.filter(isTrending=True)[:3]

    category = None
    if category_slug:
        category = Category.objects.get(slug=category_slug)
        productList = productList.filter(category=category)

    paginator = Paginator(productList,1)
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)

    categories = Category.objects.all()


    context ={
        'product_list':paged_products,
        'category_list':categoryList,
        'category':category,
        'trending_products':trending_products,
        'cities_choices':cities_choices
    }

    return render(request,'product/product_list.html',context)


def product_detail(request,product_slug):
    try:
        product = Product.objects.get(slug=product_slug)
    except Product.DoesNotExist:
        raise Http404('product does not exist')

    return render(request,'product/detail.html',{'product':product})

def search(request):
    queryset_list = Product.objects.order_by('-created')
    categories = Category.objects.all()

    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list =queryset_list.filter(city_name__icontains=city)


    if 'name' in request.GET:
        name = request.GET['name']
        if name:
            queryset_list=queryset_list.filter(name__icontains=name)

    context={
        'product_list':queryset_list,
        'cities_choices':cities_choices,
        'values':request.GET
    }
    return render(request,'product/product_list.html',context)



@login_required
def add_advertise(request):
    if request.method == 'POST':
        name = request.POST['name']
        category = request.POST['category']
        description = request.POST['description']
        brand = request.POST.get('brand','')
        price = request.POST['price']
        city_name = request.POST['city_name']
        photo_main = request.FILES['photo_main']
        photo_1 = request.FILES.get('photo_1','')
        photo_2 = request.FILES.get('photo_2','')
        photo_3 = request.FILES.get('photo_3','')
        photo_4 = request.FILES.get('photo_4','')
        photo_5 = request.FILES.get('photo_5','')
        photo_6 = request.FILES.get('photo_5','')

        cat = Category.objects.get(name=category)
        if brand:
            brand = Brand.objects.get(name=brand)
        else:
            brand = None
        

        product = Product(name=name,
                            description=description,
                            category=cat,
                            owner=request.user,
                            brand=brand,
                            price=price,
                            city_name=city_name,
                            photo_main=photo_main,
                            photo_1=photo_1,
                            photo_2=photo_2,
                            photo_3=photo_3,
                            photo_4=photo_4,
                            photo_5=photo_5,
                            )
        print(product)
        product.save()
        messages.success(request,'you have been post your advertise successfully!')

        return redirect('products:product_list')
        
       






    categories = Category.objects.all()


    context={
        'categories':categories,
        'cities_choices':cities_choices,
    }
    return render(request,'product/post-ad.html',context)

templates/product/detail.html
{% extends 'base.html' %}

{% load product_tags %}
{% load static %}

{% block content %}

<script type="text/javascript" src="{% static 'js/jquery.leanModal.min.js' %}"></script>
<link href="{% static 'css/jquery.uls.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.grid.css' %}" rel="stylesheet"/>
<link href="{% static 'css/jquery.uls.lcd.css' %}" rel="stylesheet"/>
<!-- Source -->
<script src="js/jquery.uls.data.js"></script>
<script src="js/jquery.uls.data.utils.js"></script>
<script src="js/jquery.uls.lcd.js"></script>
<script src="js/jquery.uls.languagefilter.js"></script>
<script src="js/jquery.uls.regionfilter.js"></script>
<script src="js/jquery.uls.core.js"></script>

<link rel="stylesheet" href="css/flexslider.css" media="screen" />



	<div class="single-page main-grid-border">
		<div class="container">

			<div class="product-desc">
				<div class="col-md-7 product-view">
					<h2>{{ product.name }}</h2>
					<p> <i class="glyphicon glyphicon-map-marker"></i><a href="#">state</a>, <a href="#">city</a>| Added at {{product.created}}, Ad ID: {{product.id}}</p>
					<div class="flexslider">
						<ul class="slides">
							{% if product.photo_main %}
								<li data-thumb="{{ product.photo_main.url }}">
									<img src="{{ product.photo_main.url }}" />
								</li>
							{% endif %}

							{% if product.photo_1 %}
								<li data-thumb="{{ product.photo_1.url }}">
									<img src="{{ product.photo_1.url }}" />
								</li>
							{% endif %}

							{% if product.photo_2 %}
								<li data-thumb="{{ product.photo_2.url }}">
									<img src="{{ product.photo_2.url }}" />
								</li>
							{% endif %}

							{% if product.photo_3 %}
								<li data-thumb="{{ product.photo_3.url }}">
									<img src="{{ product.photo_3.url }}" />
								</li>
							{% endif %}

							{% if product.photo_4 %}
								<li data-thumb="{{ product.photo_4.url }}">
									<img src="{{ product.photo_4.url }}" />
								</li>
							{% endif %}

							{% if product.photo_5 %}
								<li data-thumb="{{ product.photo_5.url }}">
									<img src="{{ product.photo_5.url }}" />
								</li>
							{% endif %}

							{% if product.photo_6 %}
								<li data-thumb="{{ product.photo_6.url }}">
									<img src="{{ product.photo_6.url }}" />
								</li>
							{% endif %}
						</ul>
					</div>
					<!-- FlexSlider -->
					  <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
					<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />

						<script>
					// Can also be used with $(document).ready()
					$(window).load(function() {
					  $('.flexslider').flexslider({
						animation: "slide",
						controlNav: "thumbnails"
					  });
					});
					</script>
					<!-- //FlexSlider -->
					<div class="product-details">
						<h4>Brand : <a href="#">{{product.brand.name}}</a></h4>
						<h4>Views : <strong>150</strong></h4>
						<p><strong>Display </strong>: 1.5 inch HD LCD Touch Screen</p>
						<p><strong>Summary</strong> : {{product.description}}</p>

					</div>
				</div>
				<div class="col-md-5 product-details-grid">
					<div class="item-price">
						<div class="product-price">
							<p class="p-price">Price</p>
							<h3 class="rate">$ {{product.price}}</h3>
							<div class="clearfix"></div>
						</div>
						<div class="condition">
							<p class="p-price">Condition</p>
							<h4>{{product.condition}}</h4>
							<div class="clearfix"></div>
						</div>
						<div class="itemtype">
							<p class="p-price">Item Type</p>
							<h4>Phones</h4>
							<div class="clearfix"></div>
						</div>
					</div>
					<div class="interested text-center">
						<h4>Interested in this Ad?<small> Contact the Seller!</small></h4>
						{% if user.is_authenticated %}
							<p><i class="glyphicon glyphicon-earphone"></i>{{ product.owner.profile.phone }}</p>
						{% else %}
							<p><i class="glyphicon glyphicon-earphone"></i>{{ product.owner.profile.phone|hash_Phone }}</p>
							<p><a href="{% url 'accounts:register' %}">SignUp</a> or <a href="{% url 'accounts:login' %}">SignIn</a> To see seller phone number</p>
						{% endif %}
					</div>
						<div class="tips">
						<h4>Safety Tips for Buyers</h4>
							<ol>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
								<li><a href="#">Contrary to popular belief.</a></li>
							</ol>
						</div>
				</div>
			<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--//single-page-->
{% endblock %}

templates/product/index.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
		<!-- content-starts-here -->
		<div class="content">
			<div class="categories">
				<div class="container">
				{% for category in category_list %}
					<div class="col-md-2 focus-grid">
						<a href="{% url 'products:product_list_category' category.slug %}">
							<div class="focus-border">
								<div class="focus-layout">
									<div class="focus-image"><img src="{{ category.image.url}}"></div>
									<h4 class="clrchg">{{ category.name}}</h4>
								</div>
							</div>
						</a>
					</div>
				{% endfor %}
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="trending-ads">
				<div class="container">
				<!-- slider -->
				<div class="trend-ads">
					<h2>Trending Ads</h2>
							<ul id="flexiselDemo3">
								<li>
									{% for trend_product in trending_products %}
										<div class="col-md-3 biseller-column">
											<a href="{% url 'products:product_detail' trend_product.slug%}">
												<img src="{{ trend_product.photo_main.url}}" height="250"/>
												<span class="price">&#36; {{trend_product.price|intcomma}}</span>
											</a>
											<div class="ad-info">
												<h5>{{trend_product.name}}</h5>
												<span>{{trend_product.created|naturaltime}}</span>
											</div>
										</div>
										{% endfor %}
								</li>
						</ul>
					<script type="text/javascript">
						 $(window).load(function() {
							$("#flexiselDemo3").flexisel({
								visibleItems:1,
								animationSpeed: 1000,
								autoPlay: true,
								autoPlaySpeed: 5000,
								pauseOnHover: true,
								enableResponsiveBreakpoints: true,
								responsiveBreakpoints: {
									portrait: {
										changePoint:480,
										visibleItems:1
									},
									landscape: {
										changePoint:640,
										visibleItems:1
									},
									tablet: {
										changePoint:768,
										visibleItems:1
									}
								}
							});

						});
					   </script>
					   <script type="text/javascript" src="{% static 'js/jquery.flexisel.js' %}"></script>
					</div>
			</div>
			<!-- //slider -->
			</div>
			<div class="mobile-app">
				<div class="container">
					<div class="col-md-5 app-left">
						<a href="mobileapp.html"><img src="{% static 'images/app.png' %}" alt=""></a>
					</div>
					<div class="col-md-7 app-right">
						<h3>Resale App is the <span>Easiest</span> way for Selling and buying second-hand goods</h3>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam auctor Sed bibendum varius euismod. Integer eget turpis sit amet lorem rutrum ullamcorper sed sed dui. vestibulum odio at elementum. Suspendisse et condimentum nibh.</p>
						<div class="app-buttons">
							<div class="app-button">
								<a href="#"><img src="{% static 'images/1.png' %}" alt=""></a>
							</div>
							<div class="app-button">
								<a href="#"><img src="{% static 'images/2.png' %}" alt=""></a>
							</div>
							<div class="clearfix"> </div>
						</div>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>

{% endblock %}

templates/product/post-ad.html
{% extends 'base.html' %}


{% block content %}

	<!-- Submit Ad -->
	<div class="submit-ad main-grid-border">
		<div class="container">
			<h2 class="head">Post an Ad</h2>
			<div class="post-ad-form">
				<form action="{% url 'products:add_advertise' %}" method="POST" enctype="multipart/form-data">
					{% csrf_token %}
					
					<label>Select Category <span>*</span></label>
					<select class="" name="category">
					  <option>Select Category</option>
					  {% for category in categories  %}
						  <option value="{{ category }}">{{ category }}</option>
					  {% endfor %}
					</select>
					<div class="clearfix"></div>

					<label>Ad Title <span>*</span></label>
					<input type="text" name="name" class="phone" placeholder="">
					<div class="clearfix"></div>

					<label>Ad Description <span>*</span></label>
					<textarea class="mess" name="description" placeholder="Write few lines about your product"></textarea>
					<div class="clearfix"></div>

					<label>Ad Brand</label>
					<input type="text" name="brand" class="phone" placeholder="">
					<div class="clearfix"></div>

					<label>Price</label>
					<input type="number" name="price" placeholder="">
					<div class="clearfix"></div>

					<label>Select Category <span>*</span></label>
					<select class="" name="city_name">
					  <option>Select City</option>
					  {% for key,value in cities_choices.items  %}
						  <option value="{{ key }}">{{ value }}</option>
					  {% endfor %}
					</select>
					<div class="clearfix"></div>

				<div class="upload-ad-photos">

					<label>Main Photo<span>*</span> :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file" name="photo_main"/>
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_1 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_1" />
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_2 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_2" />
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_3 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_3" />
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_4 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_4" />
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_5 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_5" />
						</div>
					</div>
					<div class="clearfix"></div>

					<label>photo_6 :</label>	
					<div class="photos-upload-view">
						<div>
							<input type="file"name="photo_6" />
						</div>
					</div>
					<div class="clearfix"></div>

				</div>
					<div class="personal-details">
						<input type="hidden" name="owner" value="{{ user }}">
						<label>Your Name <span>*</span></label>
						<input type="text" class="name" value="{{user.username}}" disabled>
						<div class="clearfix"></div>
						<label>Your Mobile No <span>*</span></label>
						<input type="text" class="phone" value="{{ user.profile.phone }}" disabled>
						<div class="clearfix"></div>
						<label>Your Email Address<span>*</span></label>
						<input type="text" class="email"  value="{{user.email}}" disabled>
						<div class="clearfix"></div>
						<p class="post-terms">By clicking <strong>post Button</strong> you accept our <a href="terms.html" target="_blank">Terms of Use </a> and <a href="privacy.html" target="_blank">Privacy Policy</a></p>
					<input type="submit" value="Post">					
					<div class="clearfix"></div>
					
					</div>
				</form>
			</div>
		</div>	
	</div>
	<!-- // Submit Ad -->

{% endblock  %}

	

templates/product/product_list.html
{% extends 'base.html' %}

{% load static %}
{% load humanize %}

{% block content %}
	<!-- Products -->
	<div class="total-ads main-grid-border">
		<div class="container">
			<div class="select-box">
				<form action="{% url 'products:search' %}" method="get">
					<div class="select-city-for-local-ads ads-list">
						<label>Select your city to see local ads</label>
							<select name="city">
											<option selected style="display:none;color:#eee;">Entire Egypt</option>
											{% for key,value in cities_choices.items %}
												<option value="{{ key }}"
												{% if key == values.city %}
													selected
												{% endif %}
												>{{value}}
												</option>
											{% endfor %}
				      </select>
					</div>
					
					<div class="search-product ads-list">
						<label>Search for a specific product</label>
						<div class="search">
							<div id="custom-search-input">
							<div class="input-group">
								<input name="name" value="{{values.name}}" type="text" class="form-control input-lg" placeholder="Buscar" />
								<span class="input-group-btn">
									<button class="btn btn-info btn-lg" type="submit">
										<i class="glyphicon glyphicon-search"></i>
									</button>
								</span>
							</div>
						</div>
						</div>
					</div>
				</form>
				<div class="clearfix"></div>
			</div>
			{% if 'search' not in request.path %}
			<div class="all-categories">
				<h3> Select your category and find the perfect ad</h3>
				<ul class="all-cat-list">
					{% for category in category_list %}
						<li>
							<a href="{% url 'products:product_list_category' category.slug %}">{{category.name}} <span class="num-of-ads">({{category.total_products}})</span>
							</a>
						</li>
					{% endfor %}
				</ul>
			</div>
			{% else %}
				<h3>({{product_list|length}})product founded</h3>
				<br>
			{% endif %}
			<ol class="breadcrumb" style="margin-bottom: 5px;">
			  <li><a href="{% url 'products:index' %}">Home</a></li>
				<li class="active">All Ads</li>
			  <li class="active">{{category.name}}</li>
			</ol>
			<div class="ads-grid">
				<div class="side-bar col-md-3">
					<div class="search-hotel">
					<h3 class="sear-head">Name contains</h3>
					<form method="get" action="{% url 'products:search' %}">
						<input type="text" name="name" placeholder="Product name..." value="{{values.name}}" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Product name...';}" required="">
						<input type="submit" value=" ">
					</form>
				</div>

				{% if 'search' not in request.path %}
				<div class="featured-ads">
					<h2 class="sear-head fer">Featured Ads</h2>
					{% for product in trending_products %}
						<div class="featured-ad">
							<a href="{% url 'products:product_detail' product.slug %}">
								<div class="featured-ad-left">
									<img src="{{product.photo_main.url}}" height="100" title="ad image" alt="" />
								</div>
								<div class="featured-ad-right">
									<h4>{{product.name}}</h4>
									<p>$ {{product.price|intcomma}}</p>
								</div>
								<div class="clearfix"></div>
							</a>
						</div>
					{% endfor %}
					<div class="clearfix"></div>
				</div>
				{% endif %}
				</div>
				<div class="ads-display col-md-9">
					<div class="wrapper">
					<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
					  <div id="myTabContent" class="tab-content">
						<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
						   <div>
												<div id="container">


								<div class="clearfix"></div>
							<ul class="list">
								{% if not product_list %}
									<h1>there is no products founded!!</h1>
								{% else %}
									{% for product in product_list %}
										<a href="{% url 'products:product_detail' product.slug %}">
											<li>
											<img src="{{ product.photo_main.url }}" title="" alt="" />
											<section class="list-left">
											<h5 class="title">{{ product.name }}</h5>
											<span class="adprice">${{ product.price|intcomma }}</span>
											<p class="catpath">{{ product.brand.name 	}}</p>
											</section>
											<section class="list-right">
											<span class="date">{{product.created|naturaltime}}</span>
											<span class="cityname">{{ product.city_name}}</span>
											</section>
											<div class="clearfix"></div>
											</li>
										</a>
									{% endfor %}
								{% endif %}
							</ul>
						</div>
							</div>
						</div>
						{% if product_list.has_other_pages %}
							<ul class="pagination pagination-sm">
								{% if product_list.has_previous %}
									<li><a href="?page={{product_list.previous_page_number}}">Prev</a></li>
								{% else %}
									<li class="disabled"><a>Prev</a></li>
								{% endif %}

								{% for num in product_list.paginator.page_range %}
									{% if product_list.number == num %}
										<li class="active"><a href="">{{num}}</a></li>
									{% else %}
										<li><a href="?page={{num}}">{{num}}</a></li>
									{% endif %}
								{% endfor %}
								{% if product_list.has_next %}
									<li><a href="?page={{product_list.next_page_number}}">Next</a></li>
								{% else %}
									<li class="disabled"><a>Next</a></li>
								{% endif %}
							</ul>
						{% endif %}
					  </div>
					</div>
				</div>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!-- // Products -->
	{% endblock %}